---
- hosts: all
  become: True
  become_user: root
  gather_facts: False
  roles:
    - bootstrap

- hosts: all
  become: True
  become_user: root
  roles:
    - bootstrap
    - apt
    - ssh
    - firewall
    - timezone
    - shell

- include: site_master.yml
- include: site_agent.yml
- include: site_bootstrap.yml
