---
docker_repo_url: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_lsb.codename }} main
docker_keyserver: hkp://p80.pool.sks-keyservers.net:80
docker_key_id: 58118E89F3A912897C070ADBF76221572C52609D
