---
- name: Add java ppa
  apt_repository:
    state: present
    repo: "ppa:webupd8team/java"
  tags:
    - java

- name: Check if java is already installed
  shell: "dpkg -l | grep oracle-java8-installer"
  register: java_check_installed
  ignore_errors: True
  changed_when: java_check_installed.rc != 0
  tags:
    - java

- name: Accept Oracle license
  shell: "echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections"
  when: java_check_installed.rc != 0
  tags:
    - java

- name: Install java8
  apt:
    state: present
    pkg: "oracle-java8-installer"
    update-cache: yes
  when: java_check_installed.rc != 0
  tags:
    - java
