---
- name: Install repository key
  apt_key:
    state: present
    keyserver: "{{ docker_keyserver }}"
    id: "{{ docker_key_id }}"
  tags:
    - docker

- name: Install remote repository
  apt_repository:
    state: present
    repo: "{{ docker_repo_url }}"
  tags:
    - docker

- name: Install docker and pip
  apt:
    state: present
    pkg: "{{ item }}"
    cache_valid_time: 3600
  with_items:
    - docker-engine
    - python-pip
  tags:
    - docker

- name: Install docker-py
  pip:
    state: present
    name: docker-py
  tags:
    - docker

- name: Load overlay kernel module
  modprobe:
    state: present
    name: overlay
  tags:
    - docker

- name: Load overlay kernel module at boot
  lineinfile:
    state: present
    dest: /etc/modules
    regexp: overlay
    line: overlay
  tags:
    - docker

- name: Create systemd file
  template:
    src: lib_systemd_system_docker.service
    dest: /lib/systemd/system/docker.service
    mode: 0644
    owner: root
    group: root
  register: systemd
  tags:
    - docker

- name: Reload systemd
  command: systemctl daemon-reload
  notify: restart docker
  when: systemd|changed
  tags:
    - docker

- name: Start and enable dockerd
  service:
    name: docker
    state: started
    enabled: True
  tags:
    - docker
