---
- name: Install required packages
  apt:
    state: present
    pkg: "{{ item }}"
  with_items:
    - unzip
    - ipset

- name: Create links for dcos since it expects stuff at the RedHat locations
  file:
    state: link
    src: "/bin/{{ item }}"
    path: "/usr/bin/{{ item }}"
  with_items:
    - mkdir
    - ln
    - tar
    - rm

- name: Create /opt/dcos directory
  file:
    path: /opt/dcos
    state: directory

- name: Download the DC/OS installer from the nginx Docker container
  get_url:
    url: "http://{{ groups['bootstrap'][0] }}/dcos_install.sh"
    dest: /opt/dcos/dcos_install.sh
    force: yes
  register: new_install_script

- name: Check if mesosphere is already installed
  stat:
    path: /opt/mesosphere
  register: mesosphere_directory

- name: Uninstall DC/OS
  command: /opt/mesosphere/bin/pkgpanda uninstall
  when: new_install_script.changed == True and mesosphere_directory.stat.exists == True

- name: Remove DC/OS
  file:
    state: absent
    path: /opt/mesosphere
  when: new_install_script.changed == True and mesosphere_directory.stat.exists == True

- name: Check if mesos-dns already stopped working
  wait_for:
    host: 0.0.0.0
    port: 53
    delay: 10
    state: stopped
  when: new_install_script.changed == True and mesosphere_directory.stat.exists == True

- name: Install DC/OS
  command: "bash dcos_install.sh {{ type }}"
  args:
    chdir: /opt/dcos
  when: new_install_script.changed == True or mesosphere_directory.stat.exists == False
